# Generated by Django 2.2.6 on 2019-10-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelpsearch',
            name='yelpCategory',
            field=models.CharField(default='Stuff', max_length=250),
        ),
        migrations.AddField(
            model_name='yelpsearch',
            name='yelpLocation',
            field=models.CharField(default='Boston', max_length=500),
        ),
    ]
