# Generated by Django 2.2.6 on 2019-10-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trends', '0002_auto_20191023_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelpsearch',
            name='yelpCategory',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='yelpsearch',
            name='yelpLocation',
            field=models.CharField(max_length=500),
        ),
    ]
