# Generated by Django 2.2.6 on 2019-10-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trends', '0003_auto_20191023_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelpsearch',
            name='yelpCategory',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yelpsearch',
            name='yelpLocation',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
