# Generated by Django 2.2.6 on 2019-10-23 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trends', '0004_auto_20191023_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelpsearch',
            name='searchParams',
            field=models.ForeignKey(blank=None, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trends.Trends'),
        ),
    ]
