# Generated by Django 2.2.6 on 2019-10-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trends', '0005_auto_20191023_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelpsearch',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
