# Generated by Django 2.2.6 on 2019-10-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trends', '0007_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='catParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
