# Generated by Django 2.2.6 on 2019-10-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trends', '0008_auto_20191025_0432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catparams',
            options={'verbose_name_plural': 'names'},
        ),
        migrations.RenameField(
            model_name='catparams',
            old_name='categories',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='catparams',
            name='location',
        ),
    ]
