# Generated by Django 2.2.6 on 2019-11-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trends', '0009_auto_20191025_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='trendParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trends', models.CharField(max_length=45)),
            ],
        ),
    ]
