# Generated by Django 2.2.6 on 2019-12-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trends', '0010_trendparams'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_places', models.ManyToManyField(blank=True, related_name='favorite_places', to='Trends.catParams')),
            ],
        ),
    ]
